version: "3.8"

services:
  postgres-db:
    image: postgres:16.1
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    env_file: ./.env.local
    ports:
      - "5432:5432"
  postgres-db-test:
    image: postgres:16.1
    env_file: ./.env.test.local
    ports:
      - 5433:5432

volumes:
  postgres-db-data:
